<?php

//Code description: Creates settings page  to enter custom email recipient and custom email subject for plugin and theme automatic update email. If not set, it will fall back to default behaviour.

//Register settings for auto-update email customization
function cae_register_settings() {
    add_option( 'cae_update_email_to', '' );
    add_option( 'cae_update_email_subject', '' );
	add_option( 'cae_update_email_from_name', '' );
    add_option( 'cae_update_email_from_email', '' );

    register_setting( 'cae_settings_group', 'cae_update_email_to' );
    register_setting( 'cae_settings_group', 'cae_update_email_subject' );
	register_setting( 'cae_settings_group', 'cae_update_email_from_name' );
	register_setting( 'cae_settings_group', 'cae_update_email_from_email' );
}
add_action( 'admin_init', 'cae_register_settings' );


//Add admin menu page
function cae_settings_menu() {
    add_options_page(
        'Auto Update Email Settings',
        'Update Email Settings',
        'manage_options',
        'cae-update-email-settings',
        'cae_settings_page'
    );
}
add_action( 'admin_menu', 'cae_settings_menu' );


//Settings page template
function cae_settings_page() {
    ?>
    <div class="wrap">
        <h1>Auto Update Email Settings</h1>

        <form method="post" action="options.php">
            <?php settings_fields( 'cae_settings_group' ); ?>
            <?php do_settings_sections( 'cae_settings_group' ); ?>

            <table class="form-table">
                <tr>
                    <th scope="row">Recipient Email</th>
                    <td>
                        <input type="email" name="cae_update_email_to"
                               value="<?php echo esc_attr( get_option('cae_update_email_to') ); ?>"
                               class="regular-text" />
                        <p class="description">Leave empty to use the default WordPress admin email.</p>
                    </td>
                </tr>
				
				<tr>
					<th scope="row">From Name</th>
					<td>
						<input type="text" name="cae_update_email_from_name"
							   value="<?php echo esc_attr( get_option('cae_update_email_from_name') ); ?>"
							   class="regular-text" />
						<p class="description">Leave empty to use the default WordPress from name.</p>
					</td>
				</tr>
				
			    <tr>
					<th scope="row">From Email</th>
					<td>
						<input type="email" name="cae_update_email_from_email"
							   value="<?php echo esc_attr( get_option('cae_update_email_from_email') ); ?>"
							   class="regular-text" />
						<p class="description">Leave empty to use the default WordPress from email.</p>
					</td>
				</tr>


                <tr>
                    <th scope="row">Email Subject</th>
                    <td>
                        <input type="text" name="cae_update_email_subject"
                               value="<?php echo esc_attr( get_option('cae_update_email_subject') ); ?>"
                               class="regular-text" />
                        <p class="description">Leave empty to use the default subject generated by WordPress.</p>
                    </td>
                </tr>
            </table>

            <?php submit_button(); ?>
        </form>
    </div>
    <?php
}


//START CUSTOMIZING EMAIL RECIPIENT AND EMAIL SUBJECT
function cae_customize_auto_update_email( $email, $type, $successful_updates, $failed_updates ) {

    // Get saved values
    $custom_to      = trim( get_option( 'cae_update_email_to' ) );
    $custom_subject = trim( get_option( 'cae_update_email_subject' ) );
	$custom_from_name     = trim( get_option( 'cae_update_email_from_name' ) );
    $custom_from_email = trim( get_option( 'cae_update_email_from_email' ) );

    // Fallback: use default admin email if none provided
    if ( ! empty( $custom_to ) ) {
        $email['to'] = $custom_to;
    }

    // Fallback: keep WordPress's default subject if not set
    if ( ! empty( $custom_subject ) ) {
        $email['subject'] = $custom_subject;
    }
	
	$default_from_name  = wp_specialchars_decode( get_bloginfo( 'name' ), ENT_QUOTES );
    $default_from_email = get_option( 'admin_email' );

    $from_name  = ! empty( $custom_from_name )  ? $custom_from_name  : $default_from_name;
    $from_email = ! empty( $custom_from_email ) ? $custom_from_email : $default_from_email;
	
	 // Build proper header
    $email['headers'][] = 'From: ' . $from_name . ' <' . $from_email . '>';

    return $email;
}
add_filter( 'auto_plugin_theme_update_email', 'cae_customize_auto_update_email', 999, 4 );
